pakyow/pakyow

pakyow-mailer/lib/mailer/mailer.rb

This is related to the following issue in premailer:
https://github.com/premailer/premailer/issues/201
I noticed this was happening in a project I was working on.  It turns out the fix is pretty simple, you just need to render the plain text version first.  
Before change:
After change:
Go Pakyow!

Don't prints styles into text emails

---

pakyow-core/lib/core/app.rb

Use current loader or new loader
This fix allows for intended use of loader to only load files that have
been changed since the last time they were loaded.

Issue #73 Possible Bug in Reloading

---

pakyow-presenter/lib/presenter/view.rb

Calling the value proc with attrs will indirectly set the value to the doc (or remove the attribute from the doc, if the value is nil), so there is no need to set it again.
See Pakyow::Presenter::Attribute#update_value

updated bind_attributes_to_doc to avoid setting value to doc twice

---

pakyow-test/lib/test_help/helpers.rb
pakyow-test/lib/test_help/simulator.rb
pakyow-test/spec/integration/routing_spec.rb
pakyow-test/spec/unit/helpers_spec.rb
pakyow-test/spec/unit/simulator_spec.rb

Adds the ability to specify the `env` configs you want to include in your simulated requests. It follows the same pattern as `params`, `cookies`, etc...
```
get '/', env: { foo: 'bar' } do |sim|
puts sim.req.env['foo'] # => 'bar'
end
```
Tests are included.

Ability to set env params on simulated requests

---

pakyow-core/lib/core/app.rb
pakyow-core/lib/core/helpers/configuring.rb
pakyow-core/lib/core/helpers/hooks.rb
pakyow-core/lib/core/helpers/running.rb
pakyow-core/spec/unit/helpers/configuring_spec.rb
pakyow-core/spec/unit/helpers/hooks_spec.rb
pakyow-core/spec/unit/helpers/running_spec.rb

Pakyow::App has been notoriously hard to test and overly complex from the beginning. This commit is the first step towards improving this part of the codebase.
The decision to move methods out of Pakyow::App into their own modules was driven out of a desire to make the code a) more testable and b) easier to understand. Each concern of the app is now contained in its own module (e.g. configuring).
Everything a developer needs to know is available right there in the module. Because there are no dependencies, the methods around a particular concern can be tested in true isolation.
Because of the scope of this refactor I wanted to open a PR and get input from others.
Next steps include:
- Writing unit tests for `Pakyow::Helpers::Running` and `Pakyow::Helpers::Hooks`
- Removing the need to …

App Refactor

---

lib/pakyow/command_line_interface.rb
lib/pakyow/commands/server.rb
spec/features/command_line_interface_spec.rb

* The backtrace produced by the LoadError really wasn't beneficial to a
user. This at least hints to the user that they may be running the
command in the wrong directly.
Now it looks like:
```sh
$ bin/pakyow server
Error: cannot load such file -- app/setup
You must run the `pakyow server` command in a Pakyow application's root directory.
```
See #131

Improve output clarity for failed server and console commands

---

lib/generators/pakyow/app/templates/app/setup.rb
lib/generators/pakyow/app/templates/middleware/logger.rb
lib/generators/pakyow/app/templates/middleware/override.rb
lib/generators/pakyow/app/templates/middleware/reloader.rb
lib/generators/pakyow/app/templates/middleware/req_path_normalizer.rb
lib/generators/pakyow/app/templates/middleware/session.rb
lib/generators/pakyow/app/templates/middleware/static.rb
pakyow-core/lib/core/base.rb
pakyow-core/lib/core/config/app.rb
pakyow-core/lib/core/config/session.rb
pakyow-core/lib/core/middleware/logger.rb
pakyow-core/lib/core/middleware/override.rb
pakyow-core/lib/core/middleware/reloader.rb
pakyow-core/lib/core/middleware/req_path_normalizer.rb
pakyow-core/lib/core/middleware/session.rb
pakyow-core/lib/core/middleware/static.rb
pakyow-core/spec/unit/config/session_config_spec.rb

Defining middleware in the generated app felt wrong.
The approach in this commit registers default middleware and allows non-critical middleware to be disabled via config options. It also adds config options for configuring sessions so that the session middleware can be handled in a consistent way.

Middleware Refactor

---

pakyow-core/lib/core/helpers/configuring.rb
pakyow-core/spec/cases/application_spec.rb

It intentionally worked in a different way, but those edges went away when we started using dotenv for specific config values. This makes more sense now. Fixes #152.

Load global config first

---

pakyow-test/lib/test_help/ext/request.rb
pakyow-test/spec/unit/ext/request_spec.rb

It now returns the original param values if pakyow.params is nil. See #151.

Fix test help params

---

pakyow-core/lib/pakyow/core/helpers/configuring.rb

Since `KeyError` is rescued when invoking a configuration block, an error of this type raised in a user's configuration block is lost, leading to head-scratching as to why things aren't working (or blowing up).
Since the error is not used, substitute and innocent noop proc for missing configuration blocks. This avoids needing to handle errors et al.
cc @bryanp

Configuration blocks mistakenly gobble up KeyErrors

---

lib/pakyow/command_line_interface.rb

When running the version command in the project, the feature is required
by the gemspec. However when the gem is built and installed, the feature
is never required so referencing Pakyow::VERSION fails.

Explicitly require version feature for CLI

---

lib/generators/pakyow/app/app_generator.rb

The relative path was broken when we moved code into the pakyow
namespace. Actually this is a really great illustration of why to avoid
require_relative.

Fix require in app generator

---

pakyow-realtime/lib/pakyow/realtime/hooks.rb

Downcases the HTTP_UPGRADE value provided by the browser when checking for "websocket". This fixes websockets in IE11, which sends the HTTP_UPGRADE value as “Websocket” (for some reason).

Downcase HTTP_UPGRADE header for comparison

---

pakyow-presenter/lib/pakyow/presenter/attributes.rb
pakyow-presenter/spec/integration/support/mixins/attr_specs.rb

Adds a new `ensure_or_deny` method that simplifies being explicit about the attrs you modify.
For example, we often do something like this to make sure a class is added/removed under the appropriate conditions:
```ruby
binding :status do
{
class: lambda { |klass|
if bindable.active?
klass.ensure('active')
else
klass.deny('active')
end
}
}
end
```
But now we can just do this:
```ruby
binding :status do
{
class: lambda { |klass|
klass.ensure_or_deny('active') { bindable.active? }
}
}
end
```

Add ensure_or_deny method to attrs

---

docs/start/installing.md

Rubygems comes preinstalled with all pakyow-supported ruby versions

Remove rubygems installation section

---

pakyow-ui/lib/pakyow/ui/mutation_store.rb

Rack::Session::Abstract::SessionHash implements a to_hash method instead of a to_h method.

use to_hash instead of to_h

---

pakyow-core/lib/pakyow/core/middleware/logger.rb

This fix is to handle the case for logging where a frozen string is passed to the logger, which is the case for Sequel.

hot fix: dup msg passed to Logger#<< (#write)

---

pakyow-support/lib/pakyow/support/configurable/config_group.rb

Use underscore prefix to avoid name conflicts for settings.

Config group attributes

---

lib/pakyow/cli.rb

This is still a WIP at this point... The tweak here was dead simple, but I'm not really sure how to correct the display of the options as discussed [here](https://github.com/pakyow/pakyow/issues/217).

Corrected syntax in help message for "server" command.

---

lib/pakyow/environment.rb

In regards to https://github.com/pakyow/pakyow/issues/255

update format of settings in environment.rb

---

pakyow-core/lib/pakyow/core/app.rb
pakyow-core/lib/pakyow/core/router.rb
pakyow-core/lib/pakyow/core/routing/route.rb
pakyow-support/lib/pakyow/support/deep_freeze.rb
pakyow-support/lib/pakyow/support/definable.rb
pakyow-support/spec/deep_freeze_spec.rb

- Adds deep_freeze as a refinement on Object and Array.
- Removes implementations of freeze for Router and Route.
In reference to https://github.com/pakyow/pakyow/issues/253

add deep_freeze refinement to support

---

pakyow-core/lib/pakyow/core/app.rb
pakyow-core/lib/pakyow/core/loader.rb
pakyow-core/lib/pakyow/core/router.rb
pakyow-core/spec/features/loading_spec.rb
pakyow-core/spec/unit/app_spec.rb
pakyow-presenter/lib/pakyow/presenter/binder.rb
pakyow-presenter/lib/pakyow/presenter/extensions/app.rb
pakyow-presenter/lib/pakyow/presenter/presenters/view.rb
pakyow-presenter/lib/pakyow/presenter/processor.rb
pakyow-support/lib/pakyow/support/class_maker.rb
pakyow-support/spec/unit/class_maker_spec.rb

Pakyow will now automatically infer names for application state (e.g. routers). The goal is to make it easier to follow a good and consistent naming convention throughout an application.
You can see a real-world, bootable example over at [pakyow/design](https://github.com/pakyow/design).
**Work that's left:**
**Further explanation:**
Given this router defined at `./backend/routing/home.rb`:
```ruby
router "/" do
get :foo, "/foo" do; end
end
```
Pakyow infers the name to be `home`. The router is available for path building as expected:
```ruby
path(:home_foo)
```
Pakyow also gives the router a nice class name. Given an app name of `example`, the assigned class name for the above router is `Example::Routing::Home`. It's identical to defining it longhand:
```ruby
Example::App.router << …
```

Inferred Naming

---

pakyow-realtime/CHANGELOG.md
pakyow-realtime/lib/pakyow/realtime/server.rb
pakyow-realtime/spec/spec_helper.rb
pakyow-ui/CHANGELOG.md
pakyow-ui/lib/pakyow/application/behavior/ui/rendering.rb
pakyow-ui/lib/pakyow/ui/framework.rb
pakyow-ui/spec/integration/behavior/timeouts_spec.rb

Using thread pools larger than 1 thread can cause changes to be applied out of order from time to time. While the executor guarantees that tasks are executed in order, it doesn't guarantee that one finished before another. This was causing odd and unpredictable behavior that was resolved by dropping down to a single thread executor.
The change to the after render hook guarantees reduces calls to the data adapter when multiple renders happen for a single request (e.g. component renders). This is safe since all renders are for the same socket id.
Unfortunately this is extremely difficult to verify reliably with a test. Fortunately this code doesn't have reason to change in the near future.

Fix bug causing data subscriptions to not expire for a web socket

---

pakyow-realtime/CHANGELOG.md
pakyow-realtime/lib/pakyow/realtime/server.rb
pakyow-realtime/lib/pakyow/realtime/websocket.rb
pakyow-realtime/spec/unit/websocket_spec.rb
pakyow-ui/spec/spec_helper.rb

I've been running this in production the last couple days and it appears to resolve the intermittent connection timeouts I was seeing. It also just feels like a better approach overall.

Move heartbeat from the server to the individual websocket instance

---

pakyow-core/lib/pakyow/cli.rb
pakyow-core/lib/pakyow/errors.rb
pakyow-core/spec/features/cli_spec.rb

Fixes #298.
**Running a project command outside of a project:**
```
$ pakyow boot
› Cannot run command `boot' outside of a pakyow project
```
**Running a global command within a project:**
```
foo  $ pakyow create
› Cannot run command `create' within a pakyow project
```

Present context-aware messages for commands run in the wrong context

---

pakyow-assets/spec/features/source_maps_spec.rb

I've noticed that our css source maps aren't always accurate. Curious if this is fixed in `sassc 2.2.1`.

Update source mappings for latest sassc

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/actions/normalizer.rb
pakyow-core/lib/pakyow/config.rb
pakyow-core/spec/unit/actions/normalizer_spec.rb
pakyow-core/spec/unit/environment/config_spec.rb

Allows Pakyow Environment to force http or https for some or all hosts.

Normalize HTTP/HTTPS

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/actions/normalizer.rb
pakyow-core/lib/pakyow/config.rb
pakyow-core/spec/unit/actions/normalizer_spec.rb
pakyow-core/spec/unit/environment/config_spec.rb

Sets the host and scheme based on `normalizer.canonical_url` config option in the environment.
```ruby
Pakyow.config.normalizer.canonical_url = "https://pakyow.com"
```

Configure normalization through a canonical uri

---

pakyow-core/spec/unit/app/connection/session/cookie_spec.rb
pakyow-presenter/spec/features/csrf_meta_tags_spec.rb
pakyow-presenter/spec/features/forms/csrf_spec.rb
pakyow-realtime/spec/features/installing_spec.rb
pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/message_verifier.rb
pakyow-support/spec/unit/message_verifier_spec.rb

Message verification fails from time to time because a url safe base64 encoded string sometimes contains `--`, which is the special join character we use when building the digest. We also want the digest to be url safe, and tilde is not used for url safe base64 encodes. So, this change replaces the existing join character `--` with a new join character `~`.

Fix message verification when digest contains `--`

---

.github/workflows/smoke-test.yml
.github/workflows/test-node.yml
.github/workflows/test-ruby-head.yml
.github/workflows/test-ruby.yml
Dockerfile
pakyow-ui/spec/spec_helper.rb
tasks/ci.rake

GitHub workflows are failing intermittently due to lack of resources when spinning up MySQL, Postgres, and Redis containers. Something must have changed, because this started all of a sudden after running fine for some time.
This commit changes our workflows to run CI on external servers. For now we'll use inexpensive preemptible instances on Google Cloud Platform, but this gives us the flexibility to easily make a change in the future--either to a different provider or just resizing instances. I also expect this to be useful for automated performance testing.
The [CI Helpers](https://github.com/pakyow/ci-helpers) handle bootstrapping ephemeral instances, uploading the code, and running a remote command. They also handle being preempted by automatically re-running. We keep startup fast by …

Run CI on external servers

---

pakyow-core/CHANGELOG.md
pakyow-core/commands/pakyow
pakyow-core/spec/unit/command_spec.rb
pakyow-support/lib/pakyow/support/system.rb
pakyow-support/spec/unit/system_spec.rb

The `pakyow` command automatically bootstraps bundler, preventing the user from having to add `bundle exec` to every command. Our previous approach was to replace the process with one that ran the binstub using `exec`. This ended up not being ideal for a couple of reasons:
1. It only worked if you ran `bundle install --binstubs`.
2. Replacing processes is slow.
This commit changes the approach by setuping up Bundler in the current process if a `Gemfile` is present. In my testing it saves ~200ms.

Bootstrap bundler without exec

---

pakyow-core/spec/features/commands/info/endpoints_spec.rb
pakyow-data/spec/features/tasks/info/sources_spec.rb
pakyow-support/lib/pakyow/support/dependencies.rb
pakyow-support/lib/pakyow/support/system.rb
pakyow-support/spec/unit/system_spec.rb

Sets `Pakyow::Support::Dependencies` up to be refactored into a new `Pakyow::Backtrace` object.

Refactor some Dependency helpers into System

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/process_manager.rb
pakyow-core/spec/unit/process_manager_spec.rb

Prevents failed processes from being restarted indefinitely.

Handle failed processes by logging and exiting with an error code

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/environment.rb
pakyow-core/spec/features/async_logger_spec.rb
pakyow-core/spec/features/global_logger_spec.rb
pakyow-core/spec/features/logger_spec.rb
pakyow-core/spec/integration/request_logging_spec.rb
pakyow-core/spec/unit/actions/restart_spec.rb
pakyow-core/spec/unit/environment_spec.rb
pakyow-presenter/spec/integration/render_nested_bindings_spec.rb
pakyow-presenter/spec/integration/transforming_with_transforms_spec.rb
spec/spec_config.rb

It's sometimes necessary to log messages prior to the environment being setup. The environment now builds a default logger / global logger on demand, which is then replaced with a properly configured logger during setup. This ensures there's always a usable logger available no matter what state the environment is in.

Setup default logger, global logger in the environment

---

pakyow-core/pakyow-core.gemspec

Temporary change until https://github.com/socketry/process-group/issues/2 is resolved.

Lock process-group to v1.1.0

---

pakyow-core/pakyow-core.gemspec

`process-group` v1.2.1 was released that should resolve the underlying issue introduced in v1.2.0.

Remove lock to process-group v1.1

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/deprecations.rb
pakyow-core/lib/pakyow/config.rb
pakyow-core/lib/pakyow/environment.rb
pakyow-core/spec/features/deprecations_spec.rb
pakyow-core/spec/unit/environment/config_spec.rb
pakyow-support/lib/pakyow/support/deprecator/reporters/log.rb
pakyow-support/spec/unit/deprecator/reporters/log_spec.rb
spec/spec_config.rb

Deprecations within a project, plugin, or framework can now be reported through the environment:
```ruby
Pakyow.deprecated :foo, "use `bar'"
=> `foo' is deprecated; solution: use `bar'
```
The environment deprecator automatically configures itself as a forwarding destination with the global deprecator. This allows libraries that might be used outside the context of the environment to simply use the global deprecator. If the larger environment is available the environment deprecator will collect all deprecations, including those reported to the global instance. 
In short, these two lines are functionally equivalent when the environment is available:
```ruby
Pakyow::Support::Deprecator.global.deprecated :foo, "use `bar'"
Pakyow.deprecated :foo, "use `bar'"
```
---

Provide an environment-level deprecator

---

pakyow-core/lib/pakyow/environment.rb
pakyow-core/lib/pakyow/logger/thread_local.rb
pakyow-core/spec/features/logger_spec.rb

This allows objects that hold a reference to the thread local logger before setup to still point to the right object and log to the appropriate logger after setup. A good example to think through is the environment deprecator. If the deprecator is used before setup, it is initialized with a reference to `Pakyow.logger`. When we overwrite the logger, the reference that the deprecator holds is the old logger instead of the new one. This change avoids the whole issue by replacing the thread local's internal logger instead of replacing the entire instance.

Replace the thread local's internal logger instead of overwriting

---

pakyow-assets/spec/features/silent_spec.rb
pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/connection.rb
pakyow-core/lib/pakyow/environment.rb
pakyow-core/spec/features/async_logger_spec.rb
pakyow-core/spec/features/logger_spec.rb
pakyow-core/spec/features/output_spec.rb
pakyow-core/spec/integration/request_logging_spec.rb
pakyow-core/spec/unit/actions/input_parser_spec.rb
pakyow-core/spec/unit/actions/normalizer_spec.rb
pakyow-core/spec/unit/app/connection_spec.rb
pakyow-core/spec/unit/app_spec.rb
pakyow-core/spec/unit/connection_spec.rb
pakyow-core/spec/unit/environment_spec.rb
pakyow-core/spec/unit/logger/formatters/shared.rb
pakyow-core/spec/unit/logger_spec.rb
pakyow-data/spec/features/tasks/bootstrap_spec.rb
pakyow-data/spec/features/tasks/reset_spec.rb
pakyow-realtime/lib/pakyow/realtime/websocket.rb
pakyow-routing/spec/unit/security/base_spec.rb
pakyow-routing/spec/unit/security/csrf/verify_same_origin_spec.rb
spec/spec_config.rb

`Pakyow::output` more accurately describes what this object is.

Deprecate Pakyow::global_logger in favor of Pakyow::output

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/running.rb
pakyow-core/lib/pakyow/process.rb
pakyow-core/lib/pakyow/process_manager.rb
pakyow-core/spec/unit/process_manager_spec.rb
pakyow-core/spec/unit/process_spec.rb

Introduces a few small optimizations and improvements to the `Pakyow::ProcessManager` internals. Also simplifies the public api to use a new `Pakyow::Process` value object. This api change is introduced in a backwards-compatible way with a deprecation.

Improve Pakyow::ProcessManager

---

pakyow-core/lib/pakyow/behavior/running.rb
pakyow-core/lib/pakyow/behavior/watching.rb
pakyow-core/lib/pakyow/environment.rb
pakyow-core/lib/pakyow/logger/thread_local.rb
pakyow-core/lib/pakyow/task.rb
pakyow-core/spec/features/initializers_spec.rb
pakyow-data/lib/pakyow/data/connection.rb
pakyow-data/lib/pakyow/data/subscribers.rb
pakyow-data/lib/pakyow/data/subscribers/adapters/memory.rb
pakyow-data/lib/pakyow/data/subscribers/adapters/redis.rb
pakyow-presenter/lib/pakyow/presenter/renderer.rb
pakyow-realtime/lib/pakyow/application/behavior/realtime/server.rb
pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/configurable/config.rb
pakyow-support/lib/pakyow/support/configurable/setting.rb
pakyow-support/lib/pakyow/support/deep_freeze.rb
pakyow-support/spec/unit/deep_freeze_spec.rb
pakyow-ui/lib/pakyow/ui/framework.rb

Allows objects to insulate themselves from a deep freeze. For example, an object may want to freeze some internal state but allow other bits to be changed even after the parent is frozen:
```ruby
class ObjectWithStatus
attr_reader :status
def initialize
@status, @state = Status.new, []
end
def <<(object)
@state << object
end
class Status
...
end
end
instance = ObjectWithStatus.new
instance.deep_freeze
instance.status.frozen?
instance << :bar
```

Insulate from deep freezing

---

pakyow-assets/lib/pakyow/application/behavior/assets/externals.rb
pakyow-assets/spec/features/externals_spec.rb
pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/application/behavior/restarting.rb
pakyow-core/lib/pakyow/behavior/restarting.rb
pakyow-core/lib/pakyow/behavior/running.rb
pakyow-support/lib/pakyow/support/system.rb
spec/smoke/respawn_spec.rb
spec/smoke/restart_spec.rb
spec/smoke/startup_spec.rb
spec/smoke_helper.rb

* Make watch paths relative to environment and/or application root.
* Close the bound endpoint on shutdown so the port can be reused by respawns.
* Add smoke tests for restarts and respawns.

Resolve several issues with respawns, restarts

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/actions/logger.rb
pakyow-core/lib/pakyow/connection.rb
pakyow-core/lib/pakyow/environment.rb
pakyow-core/lib/pakyow/logger.rb
pakyow-core/lib/pakyow/logger/thread_local.rb
pakyow-core/spec/unit/actions/logger_spec.rb
pakyow-core/spec/unit/app_spec.rb
pakyow-core/spec/unit/connection/shared_examples/stream.rb
pakyow-core/spec/unit/connection_spec.rb
pakyow-core/spec/unit/logger/thread_local_spec.rb
pakyow-core/spec/unit/logger_spec.rb
pakyow-realtime/lib/pakyow/realtime/websocket.rb
pakyow-realtime/spec/unit/websocket_spec.rb
pakyow-support/CHANGELOG.md
spec/spec_config.rb

* Initialize `Pakyow::Logger::ThreadLocal` with the thread local key, and set the local logger.
* Support thread safe silencing via `Pakyow::Logger::ThreadLocal#silence`.
* Deprecate `Pakyow::Logger#silence` in favor of `Pakyow::Logger::ThreadLocal#silence`.

Improve the thread local logger

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/restarting.rb
pakyow-core/lib/pakyow/behavior/running.rb
pakyow-core/lib/pakyow/behavior/watching.rb
pakyow-core/lib/pakyow/process_manager.rb
pakyow-core/lib/pakyow/processes/proxy.rb
pakyow-core/lib/pakyow/processes/server.rb
pakyow-core/spec/integration/running/async_spec.rb
pakyow-core/spec/integration/running/hooks_spec.rb
pakyow-support/lib/pakyow/support/deep_freeze.rb
pakyow-support/spec/unit/deep_freeze_spec.rb

Introduces several (mostly minor) changes to environment run. The most consequential change is that an async reactor is now available in `on :run` hooks. This allows async tasks to run alongside the environment. We'll use this for running the new async filewatcher currently in development.

Improve environment run

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/running.rb
pakyow-core/lib/pakyow/environment.rb
pakyow-core/lib/pakyow/processes/proxy.rb
pakyow-core/lib/pakyow/processes/server.rb
spec/smoke/frozen_spec.rb
spec/spec_config.rb

This allows all environment/application state to be shared across processes, reducing the overall memory footprint substantially (4x for the pakyow.com app).
Also deprecates the `freeze_on_boot` config option. We don't want to support bad patterns, e.g. use this plugin but make sure not to freeze the environment. This is a crucial security feature.

Boot the environment once, prior to forking child processes

---

pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/deprecator.rb
pakyow-support/spec/unit/deprecator_spec.rb

Allows deprecations to be ignored during the execution of a block:
```ruby
deprecator = Pakyow::Support::Deprecator.new(
Pakyow::Support::Deprecator::Reporters::Log(logger: Pakyow.logger)
)
deprecator.ignore do
deprecator.deprecated Foo.new, :bar, "use `baz'"
end
```
Implemented in a thread safe manner.

Add Deprecator#ignore

---

pakyow-core/lib/pakyow/environment.rb
pakyow-core/lib/pakyow/logger.rb
pakyow-core/lib/pakyow/logger/thread_local.rb
pakyow-core/lib/pakyow/process_manager.rb
pakyow-core/lib/pakyow/processes/proxy.rb
pakyow-core/lib/pakyow/processes/server.rb
pakyow-core/spec/features/deprecations_spec.rb
pakyow-core/spec/unit/environment_spec.rb
pakyow-core/spec/unit/logger/thread_local_spec.rb
pakyow-core/spec/unit/logger_spec.rb
pakyow-core/spec/unit/process_manager_spec.rb
pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/deep_freeze.rb
pakyow-support/lib/pakyow/support/deprecatable.rb
pakyow-support/lib/pakyow/support/deprecator.rb
pakyow-support/lib/pakyow/support/deprecator/reporters/log.rb
pakyow-support/lib/pakyow/support/deprecator/reporters/null.rb
pakyow-support/lib/pakyow/support/deprecator/reporters/warn.rb
pakyow-support/spec/features/deprecatable/class_spec.rb
pakyow-support/spec/features/deprecatable/method_spec.rb
pakyow-support/spec/features/deprecatable/module_spec.rb
pakyow-support/spec/features/deprecator_spec.rb
pakyow-support/spec/unit/deep_freeze_spec.rb
pakyow-support/spec/unit/deprecator_spec.rb

`Pakyow::Support::Deprecatable` makes it easier to deprecate a class, module, or method.
```ruby
class DeprecatedClass
extend Pakyow::Support::Deprecatable
deprecate
end
DeprecatedClass.new
=> [deprecation] `DeprecatedClass' is deprecated; solution: do not use
```
Just like using `Deprecator#deprecated` directly, a custom solution can be passed:
```ruby
class DeprecatedClass
extend Pakyow::Support::Deprecatable
deprecate solution: "use `OtherClass'"
end
DeprecatedClass.new
=> [deprecation] `DeprecatedClass' is deprecated; solution: use `OtherClass'
```
For clarity, this PR also changes the method signature of `Deprecator#deprecated` to accept `solution` as an explicit, required keyword argument.

Introduce Deprecatable

---

pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/extension.rb
pakyow-support/spec/features/extensions/dependencies_spec.rb
pakyow-support/spec/features/extensions/restrictions_spec.rb

Extensions can now define their dependencies. When the extension is included, its dependencies will be included into or will extend the including class. This is done safely, meaning if the including object already has the dependency it will not be included or extended again.
```ruby
module ExtensionDependency
extend Pakyow::Support::Extension
apply_extension do
perform_some_destructive_setup
end
...
end
module SomeExtension
extend Pakyow::Support::Extension
include_dependency ExtensionDependency
...
end
class SomeClass
#
include ExtensionDependency
#
include SomeExtension
end
```

Extension dependencies

---

pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/configurable.rb
pakyow-support/lib/pakyow/support/extension.rb
pakyow-support/lib/pakyow/support/hookable.rb
pakyow-support/spec/features/extensions/common_methods_spec.rb

Lets extensions define methods both on the including object and its class.
```ruby
module SomeExtension
extend Pakyow::Support::Extension
common_methods do
def foo
"foo"
end
end
end
class SomeClass
include SomeExtension
end
SomeClass.foo
=> "foo"
SomeClass.new.foo
=> "foo"
```

Add a common methods pattern to extensions

---

pakyow-core/lib/pakyow/application/behavior/helpers.rb
pakyow-core/lib/pakyow/application/behavior/isolating.rb
pakyow-core/lib/pakyow/application/behavior/operations.rb
pakyow-core/lib/pakyow/helper.rb
pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/isolable.rb
pakyow-support/spec/features/isolable_spec.rb

`Pakyow::Support::Isolable` lets you create isolated classes and modules within an object.
```ruby
class Controller
...
end
class Application
include Pakyow::Support::Isolable
isolate Controller do
def self.some_behavior
puts "it works"
end
end
end
#
Application::Controller.ancestors.include?(Controller)
=> true
#
Application::Controller.some_behavior
=> it works
#
Controller.some_behavior
=> NoMethodError (undefined method `some_behavior' for Controller:Class)
```

Introduce Isolable, properly isolate helpers, operations

---

pakyow-core/lib/pakyow/application/behavior/pipeline.rb
pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/pipeline.rb
pakyow-support/spec/integration/pipeline_spec.rb

Allows pipeline actions to be defined when initializing a pipelined object, but not after.

Register pipeline actions during initialization

---

pakyow-assets/lib/pakyow/application/actions/assets/public.rb
pakyow-assets/lib/pakyow/application/behavior/assets.rb
pakyow-assets/lib/pakyow/application/behavior/assets/packs.rb
pakyow-assets/lib/pakyow/application/config/assets.rb
pakyow-assets/lib/pakyow/assets/asset.rb
pakyow-assets/lib/pakyow/assets/pack.rb
pakyow-assets/lib/pakyow/assets/precompiler.rb
pakyow-assets/spec/features/plugins/precompiling_spec.rb
pakyow-assets/spec/features/plugins/serving_spec.rb
pakyow-assets/spec/unit/types/sass_spec.rb
pakyow-assets/spec/unit/types/scss_spec.rb
pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/application/behavior/endpoints.rb
pakyow-core/lib/pakyow/endpoints.rb
pakyow-core/lib/pakyow/plugin.rb
pakyow-core/lib/pakyow/plugin/state.rb
pakyow-core/spec/features/plugins/helpers_spec.rb
pakyow-core/spec/unit/endpoints_spec.rb
pakyow-presenter/lib/pakyow/plugin/helpers/presenter/rendering.rb
pakyow-presenter/lib/pakyow/presenter/renderer.rb
pakyow-presenter/spec/features/endpoints/anchor_spec.rb
pakyow-presenter/spec/features/forms/csrf_spec.rb
pakyow-routing/CHANGELOG.md
pakyow-routing/lib/pakyow/routing/controller.rb
pakyow-routing/lib/pakyow/routing/framework.rb
pakyow-routing/spec/features/path_building_spec.rb
pakyow-routing/spec/features/redirecting_spec.rb
pakyow-routing/spec/features/rerouting_spec.rb
pakyow-routing/spec/features/security/redirecting_spec.rb

Endpoints for apps mounted at non-root paths are now exposed correctly. 
Note that because this fix requires a significant change to how endpoints are registered (including a deprecation) it won't be backported to v1.0 and will be released with v1.1.

Fix app-relative endpoints

---

pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/hookable.rb

This had the unintended side-effect of making any hookable object enumerable, which can cause downstream issues.

Remove Enumerable from Hookable

---

pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/deprecatable.rb
pakyow-support/spec/features/deprecatable/method_spec.rb

Fixing this edge-case requires building the deprecation reference at runtime rather than at the time the deprecated method override is defined.

Report deprecations correctly for previously anonymous classes

---

pakyow-core/lib/pakyow/config.rb
pakyow-core/lib/pakyow/processes/proxy.rb
pakyow-core/lib/pakyow/processes/server.rb
pakyow-core/spec/deprecations/environment/config/freeze_on_boot_spec.rb
pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/configurable/config.rb
pakyow-support/spec/integration/configurable/deprecating_spec.rb

Allows config groups and settings to be deprecated. Reading/Writing the value of a deprecated setting, or a setting within a deprecated group, will report a deprecation to the global deprecator.
Replaces #350.

Introduce config deprecations

---

pakyow-data/CHANGELOG.md
pakyow-data/lib/pakyow/data/container.rb
pakyow-data/lib/pakyow/data/sources/relational.rb
pakyow-data/spec/features/sources/relational/shared_examples/results.rb

If a data source is connected to a table with lots of columns, only values that the source explicitly defines as attributes will be included in the result set. We don't want unexpected values to leak in!

Only include values for attributes in relational results

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/verification.rb
pakyow-core/lib/pakyow/verifier.rb

This was terribly inefficient and, as it turns out, unnecessary.

Avoid deep duping during verification

---

pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/inspectable.rb
pakyow-support/spec/unit/inspectable_spec.rb

Gives `Inspectable` objects a way to opt out of inspecting specific object state. To support this, `Inspectable` objects now inspect all instance variables by default (matching `Kernel#inspect`).

Uninspectable

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/verification.rb
pakyow-core/lib/pakyow/operation.rb
pakyow-core/spec/features/verification/class_level_spec.rb
pakyow-core/spec/features/verification/dynamic_instance_spec.rb
pakyow-routing/lib/pakyow/routing/controller/behavior/param_verification.rb
pakyow-routing/spec/features/verification_spec.rb

Introduces class-level verifiers, making it possible to define verifiers on a verifiable class and perform verification on an instance of the verifiable class. Here's an example:
```ruby
class SomeObject
include Pakyow::Behavior::Verification
#
verifies :values
#
required :foo
#
verify :permissive do
optional :foo
end
attr_reader :values
def initialize(type = :strict, **values)
@values = values
case type
when :strict
verify
else
verify type
end
end
end
SomeObject.new(foo: "foo", bar: "bar").values
=> { foo: "foo" }
SomeObject.new(bar: "bar")
=> Pakyow::InvalidData
SomeObject.new(:permissive, bar: "bar").values
=> {}
```
**Operations, Controllers**
This PR also makes Operations and Controllers compatible with this pattern. Controllers should see a performance improvement since …

Introduce class-level verifiers

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/operation.rb
pakyow-core/lib/pakyow/verifier.rb
pakyow-core/spec/features/operation/getters_setters_spec.rb

This is a bit of an optimization and will allow aspects of an operation's api to be deprecated.

Define public readers and private writers for verified operation values

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/connection.rb
pakyow-core/lib/pakyow/rack/compatibility.rb
pakyow-core/spec/unit/connection/shared_examples/headers.rb
pakyow-routing/spec/features/routing_spec.rb

Provides a workaround for https://github.com/socketry/protocol-http1/issues/5.

Typecast header values to strings

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/running.rb
pakyow-core/lib/pakyow/environment.rb
pakyow-core/spec/features/app/creating_spec.rb
pakyow-core/spec/features/requests_spec.rb
pakyow-core/spec/integration/request_logging_spec.rb
pakyow-core/spec/unit/environment_spec.rb
pakyow-realtime/spec/features/persisting_state_spec.rb
spec/context/app_context.rb

Makes it easier to interact with the environment in any of its key startup phases:
* `load`: Loads and configures the environment.
* `setup`: Sets up internal state, including applications. Introspection can be performed on the environment at this point, but it isn't completely ready to use (e.g. database connections are not established during the `setup` phase).
* `boot`: Fully boots the environment so that it's ready to use.
* `run`: Boots the environment and starts all registered processes.
Calling a phase will automatically trigger all the phases underneath it.

Improve environment startup

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/environment.rb
pakyow-core/spec/unit/environment_spec.rb

The defensiveness around this continues to make adding new features more difficult. Since we don't actually have a use-case for running applications that aren't Pakyow Applications, removing this seems to be the right decision.

Assume all mounted applications are instances of Pakyow::Application

---

pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/definable/registry.rb
pakyow-support/spec/features/definable_spec.rb

Note that the test case added here does not actually fail with the old approach. I wasn't able to see this fail outside of a complex real-world case that was difficult to reproduce. Adding an explicit test case for ordering felt like the next best option.

Ensure that defined state maintains the original definition order

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/dispatching.rb
pakyow-core/spec/features/dispatch_hooks_spec.rb
pakyow-core/spec/unit/environment/events_spec.rb

Dispatch is a terminal action, meaning it should always be the last action called. But sometimes it's necessary to perform work after dispatch. This change introduces a conceptual model for these cases that's separate from that of actions: any work done in a dispatch hook is considered to be part of the dispatch action itself.

Introduce a dispatch event to the environment

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/application.rb
pakyow-core/lib/pakyow/behavior/dispatching.rb
pakyow-core/spec/features/app/accept_spec.rb

By default, applications accept a connection if the connection path starts with the application path. This can be overridden as necessary through a new `Pakyow::Application#accept`? method.

Let applications define connection acceptance with an `#accept?` method

---

pakyow-assets/CHANGELOG.md
pakyow-assets/lib/pakyow/application/behavior/assets/types/js.rb
pakyow-assets/lib/pakyow/assets/babel.rb
pakyow-assets/lib/pakyow/assets/script.rb
pakyow-assets/lib/pakyow/assets/scripts/babel.rb
pakyow-assets/lib/pakyow/assets/types/js.rb
pakyow-assets/pakyow-assets.gemspec
pakyow-assets/spec/unit/babel_spec.rb
pakyow-assets/spec/unit/scripts/babel_spec.rb
pakyow-assets/spec/unit/types/js_spec.rb
spec/spec_config.rb

This makes `pakyow/assets` fully reliant on `mini_racer`. Goodbye `execjs`!

Refactor Babel to be a Pakyow::Assets::Script

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/rescuing.rb
pakyow-core/lib/pakyow/behavior/running.rb
pakyow-core/lib/pakyow/environment.rb
pakyow-core/lib/pakyow/errors.rb
pakyow-core/spec/features/rescuing_spec.rb
pakyow-core/spec/features/running_spec.rb
pakyow-core/spec/unit/environment/config_spec.rb
pakyow-data/spec/features/migrations/auto_migrate_spec.rb
spec/smoke/rescues/environment_spec.rb
spec/smoke_helper.rb
spec/spec_config.rb

If an exception occurs when running the environment, it reports the error and boots into rescue mode. When in rescue mode a single `rescued` action is called that triggers a 500 error.

Add the rescue pattern to the environment

---

.rspec
pakyow-core/lib/pakyow/application.rb
pakyow-core/lib/pakyow/application/behavior/rescuing.rb
pakyow-core/lib/pakyow/application/connection.rb
pakyow-core/spec/unit/app/connection_spec.rb
pakyow-presenter/CHANGELOG.md
pakyow-presenter/lib/pakyow/application/behavior/presenter/error_rendering.rb
pakyow-presenter/lib/pakyow/application/behavior/presenter/initializing.rb
pakyow-presenter/lib/pakyow/presenter/framework.rb
spec/smoke/rescues/application_spec.rb
spec/spec_config.rb

This guarantees that error views will be rendered in rescue mode, even if presenter isn't setup.

Render normal error views when rescued

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/operation.rb
pakyow-core/spec/features/operation/arguments_spec.rb

`Pakyow::Operation#perform` now passes arguments through its internal pipeline. This allows an instance of an operation to be created with some initial state and be called multiple times, each time with different call-time state.
```ruby
operation :hello do
optional :greeting, default: "hello"
action do |target|
logger << "#{greeting} #{target}"
end
end
operation = operations(:hello).new
operation.perform("web")
```

Pass arguments through operations

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/logger/formatters/logfmt.rb

This was causing events to be jumbled in high-traffic production deployments.

Output logfmt events in a single write

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/runnable/container/strategies/base.rb
spec/smoke/formations_spec.rb
spec/smoke_helper.rb

Services deep freeze the environment on boot, which was causing a hash replacement error in some situations. The error stemmed from freezing the `@services` hash in the `Formation` class. We iterate over this object to start each service, then deep freezing causes the services hash to be replaced while we're iterating. This change iterates over local state instead.

Prevent deep freeze error when running formations

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/runnable/notifier.rb
pakyow-core/spec/integration/runnable/container/signaling_spec.rb
pakyow-core/spec/integration/runnable/container/success_spec.rb
pakyow-core/spec/integration/runnable/shared.rb

The way we stopped internal container notifiers was too harsh and caused issues, particularly in Ruby 2.5.8. This PR is an attempt to resolve these issues by stopping more cleanly. It also resolves several intermittent test failures.

Stop container notifiers more cleanly

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/generator.rb
pakyow-core/lib/pakyow/logger/thread_local.rb
pakyow-core/lib/pakyow/operation.rb
pakyow-core/spec/expectations/cli/debug
pakyow-core/spec/features/operation/result_spec.rb
pakyow-core/spec/unit/logger/thread_local_spec.rb
pakyow-presenter/spec/integration/empty_binding_scope_spec.rb
pakyow-realtime/spec/features/persisting_state_spec.rb
pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/deprecator.rb
pakyow-support/lib/pakyow/support/inspectable.rb
pakyow-support/lib/pakyow/support/pipeline.rb
pakyow-support/lib/pakyow/support/pipeline/internal.rb
pakyow-support/lib/pakyow/support/pipeline/object.rb
pakyow-support/lib/pakyow/support/thread_localizer.rb
pakyow-support/lib/pakyow/support/thread_localizer/store.rb
pakyow-support/spec/integration/pipeline/arguments_spec.rb
pakyow-support/spec/integration/pipeline/instance_spec.rb
pakyow-support/spec/integration/pipeline/keyword_arguments_spec.rb
pakyow-support/spec/integration/pipeline/mixed_arguments_spec.rb
pakyow-support/spec/integration/pipeline/nested_spec.rb
pakyow-support/spec/integration/pipeline/reverse_spec.rb
pakyow-support/spec/integration/pipeline/stateless_spec.rb
pakyow-support/spec/integration/pipeline/value_spec.rb
pakyow-support/spec/integration/pipeline_spec.rb
pakyow-support/spec/unit/thread_localizer_spec.rb
spec/spec_config.rb

When operations are called, the return value of the last action is now exposed as `result`:
```ruby
operation :foo do
action do |value|
value.reverse
end
end
operation = operations(:foo).new
operation.perform("foo")
operation.result
=> "oof"
```
Operations use the new `Pakyow::Support::ThreadLocalizer` module for making results thread safe.
Child threads inherit the latest result from the operation:
```ruby
operation.perform("foo")
Thread.new do
operation.result
=> "oof"
end
```
If the operation is performed in a thread, a new result is stored for the thread without altering the parent:
```ruby
operation.perform("foo")
Thread.new do
operation.perform("bar").result
=> "rab"
end
operation.result
=> "oof"
```
`Pakyow::Support::ThreadLocalizer` takes care of cleaning up instance-localized …

Expose results from operations

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/environment.rb
pakyow-core/spec/features/app/envar_config_spec.rb
pakyow-core/spec/features/envar_config_spec.rb
pakyow-support/CHANGELOG.md
pakyow-support/lib/pakyow/support/configurable.rb
pakyow-support/lib/pakyow/support/configurable/config.rb
pakyow-support/lib/pakyow/support/configurable/config/behavior/defining.rb
pakyow-support/lib/pakyow/support/configurable/setting.rb
pakyow-support/spec/integration/configurable/environment_variables_spec.rb

Allows configuration to be set through environment variables. This is supported for both the environment and applications.
Here's how to set the default server count in the environment:
```
PWENV__RUNNABLE__SERVER__COUNT=3
```
Here's how to set the application root for an application named `example`:
```
PWAPP__EXAMPLE__ROOT=some/path
```
Environment variables always take precedence over locally configured values.

Configure through environment variables

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/connection.rb
pakyow-core/spec/unit/connection/shared_examples/subdomains.rb
pakyow-core/spec/unit/connection_spec.rb

Also introduces `Connection#subdomains` for getting subdomains as an array.

Return multi-level subdomains from the connection

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/environment.rb
pakyow-core/spec/unit/environment/config/runnable/watcher_spec.rb

Disable this by default since most deployments won't use this feature and it consumes a noticeable amount of resources.

Disable the filewatcher in production and ludicrous modes

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/behavior/running.rb
pakyow-core/lib/pakyow/runnable/container/strategies/base.rb
pakyow-core/spec/unit/containers/environment/services/server_spec.rb

Fixes an issue where running a formation that does not specify a service count falls back to the wrong value in production:
```
pakyow boot --formation "environment.server"
```
This now correctly runs `5` processes, while currently it runs only `1`.

Load the environment before determining the server service count

---

pakyow-assets/pakyow-assets.gemspec

Hi @bryanp,
This `PR` upgrade `mini_racer` to **0.3**.
It appears that **0.2** is not compilable on `alpine`, so `pakyow` is **NOT** usable if :
+ run on container (`kubernetes` or else)
+ use `alpine`
Regards,

Upgrade mini_racer, to compile on alpine

---

pakyow-core/CHANGELOG.md
pakyow-core/lib/pakyow/actions/limiter.rb
pakyow-core/lib/pakyow/behavior/restarting.rb
pakyow-core/lib/pakyow/connection.rb
pakyow-core/lib/pakyow/environment.rb
pakyow-core/lib/pakyow/errors.rb
pakyow-core/lib/pakyow/handleable/behavior/defaults/request_too_large.rb
pakyow-core/spec/features/limiting_spec.rb
pakyow-core/spec/unit/environment/config/limiter_spec.rb
pakyow-core/spec/unit/environment_spec.rb
pakyow-presenter/lib/pakyow/presenter/view.rb
pakyow-presenter/spec/integration/accessing_view_attributes_spec.rb

The new limiter action provides a way to limit the size of requests accepted by the Pakyow Environment. It can be used by setting the new `config.limiter.length` option to the maximum request length (expressed in bytes).

Introduce the limiter action for limiting request body size

---

core/CHANGELOG.md
core/lib/pakyow/actions/restart.rb
core/lib/pakyow/connection.rb

Fixes a double-param parsing issue introduced by #529, while continuing to solve the original bug.

Resolve an issue causing params to be parsed twice

---

frameworks/presenter/CHANGELOG.md
frameworks/presenter/lib/pakyow/presenter/renderer/behavior/render_components.rb

Component renders are tricky because we don't want exposures to be shared. Until now we've duped the connection object for each component render. While this does prevent leaky exposures it's a bit heavy-handed. This PR introduces a lighter approach by creating a new connection object that inherits all connection state but dupes the `values` object.

Improve component rendering performance by avoiding connection duping

---

core/CHANGELOG.md
core/lib/pakyow/behavior/running.rb
core/spec/unit/containers/environment/services/server_spec.rb
core/spec/unit/containers/server/services/endpoint_spec.rb
spec/smoke/endpoint_service_siblings_spec.rb
support/lib/pakyow/support/deep_dup.rb
support/spec/unit/deep_dup_spec.rb

This change restructures containers to allow running other services alongside it. Here's the full map:
```
supervisor           (container)
environment          (service)
environment      (container)
server           (service)
server       (container)
endpoint     (service)
...
...
...
```
The `server` container and `endpoint` service are completely new. The `endpoint` service takes the place of what the `server` service is currently, with the `server` service becoming simply a supervisor for the new `server` container.
The `server` container is run with the `threaded` strategy, meaning each service in the `server` container runs in a separate thread but within a single process. This allows services right alongside the endpoint, opening the door to some interesting patterns. For example, …

Restructure containers to support running other services alongside servers

---

core/CHANGELOG.md
core/lib/pakyow/behavior/running.rb
core/lib/pakyow/runnable/container/strategies/async.rb
core/lib/pakyow/runnable/container/strategies/base.rb
core/lib/pakyow/runnable/container/strategies/forked.rb
core/lib/pakyow/runnable/container/strategies/threaded.rb
core/lib/pakyow/runnable/service.rb
core/lib/pakyow/server.rb
core/spec/integration/runnable/container/restarting_spec.rb
core/spec/integration/runnable/container/signaling_spec.rb
core/spec/integration/runnable/container/stopping_spec.rb
core/spec/integration/runnable/shared.rb
core/spec/unit/containers/server/services/endpoint_spec.rb
core/spec/unit/server_spec.rb
frameworks/assets/spec/integration/services/externals_spec.rb

Improves the container shutdown process so that services are given an opportunity to shutdown gracefully. In brief:
* Ask the container to shutdown (e.g. by sending `INT` to the container process).
* Container stops each service, calling the `shutdown` hook defined by each service.
* If the service has not stopped within the configured timeout, force it to stop.
The `perform` loop is not interrupted for graceful shutdowns, giving `shutdown` a chance to stop the loop and cleanup. If a service is forced to stop, the `shutdown` hook is not invoked and the `perform` loop is interrupted immediately.
We now use this internally in the `endpoint` service to close the endpoint when the service stops. This sets us up to further improve endpoint shutdowns by waiting on connections to finish without …

Gracefully shutdown containers and their services

---

.github/workflows/smoke-test.yml
.github/workflows/standardrb.yml
.github/workflows/test-ruby.yml
core/CHANGELOG.md
core/pakyow-core.gemspec
frameworks/assets/CHANGELOG.md
frameworks/assets/pakyow-assets.gemspec
frameworks/data/CHANGELOG.md
frameworks/data/pakyow-data.gemspec
frameworks/form/CHANGELOG.md
frameworks/form/pakyow-form.gemspec
frameworks/mailer/CHANGELOG.md
frameworks/mailer/pakyow-mailer.gemspec
frameworks/presenter/CHANGELOG.md
frameworks/presenter/pakyow-presenter.gemspec
frameworks/realtime/CHANGELOG.md
frameworks/realtime/pakyow-realtime.gemspec
frameworks/reflection/CHANGELOG.md
frameworks/reflection/pakyow-reflection.gemspec
frameworks/routing/CHANGELOG.md
frameworks/routing/pakyow-routing.gemspec
frameworks/ui/CHANGELOG.md
frameworks/ui/pakyow-ui.gemspec
pakyow.gemspec
support/CHANGELOG.md
support/pakyow-support.gemspec

Ruby 2.5 will likely be EOL by the time the next release drops, so let's go ahead and drop support. This will also resolve some segfaults that I've only seen in Ruby 2.5 related to object finalizers.

Drop Ruby 2.5 Support

---

core/CHANGELOG.md
core/lib/pakyow/behavior/running.rb
core/lib/pakyow/runnable/container/strategies/async.rb
core/lib/pakyow/runnable/container/strategies/base.rb
core/lib/pakyow/runnable/container/strategies/forked.rb
core/lib/pakyow/runnable/container/strategies/hybrid.rb
core/lib/pakyow/runnable/container/strategies/threaded.rb
core/lib/pakyow/runnable/notifier.rb
core/lib/pakyow/runnable/service.rb
core/spec/integration/runnable/container/restarting_spec.rb
core/spec/integration/runnable/container/signaling_spec.rb
core/spec/integration/runnable/container/stopping_spec.rb
core/spec/unit/runnable/service_spec.rb

Introduces service notifiers, allowing messages to be passed to a service from anywhere.
This change also fixes an issue where shutdown hooks for forked services are called in the trap context.

Stop services with the notifier pattern

---

core/CHANGELOG.md
core/lib/pakyow/runnable/container/strategies/forked.rb
core/lib/pakyow/runnable/container/strategies/hybrid.rb
core/lib/pakyow/runnable/service.rb
core/lib/pakyow/server.rb
core/spec/integration/runnable/container/stopping_spec.rb
core/spec/unit/runnable/service_spec.rb
frameworks/realtime/lib/pakyow/realtime.rb
frameworks/realtime/spec/unit/containers/server/websockets_spec.rb

Some services (like the `websockets` service) block the async reactor, preventing the stop message from being received. We now detect what services have blocked the reactor and shut them down from the main shutdown context.

Gracefully stop services that have blocked the reactor

---

core/CHANGELOG.md
core/lib/pakyow/runnable/container.rb
core/lib/pakyow/runnable/notifier.rb
core/spec/unit/runnable/container_spec.rb

Improves the reliability of signaling container processes.
The other commit are inconsequential and came out of some debugging related to the functional change.

Run containers in their own process groups

---

core/CHANGELOG.md
core/lib/pakyow/loader/context.rb
core/spec/integration/loader/definable_state_spec.rb
core/spec/integration/loader/support/definable_state/comments_only.rb

Fixes a bug rebuilding the source for loaded files when the file only contained comments.

Load comment-only files

---

core/CHANGELOG.md
core/lib/pakyow/commands/boot.rb
core/lib/pakyow/commands/create.rb
core/lib/pakyow/commands/create/application.rb
core/lib/pakyow/generators/application.rb
core/lib/pakyow/loader/context.rb
core/spec/expectations/commands/boot/help
core/spec/expectations/commands/create/application/help
core/spec/expectations/commands/create/help
core/spec/expectations/commands/prototype/help
core/spec/integration/loader/definable_state_spec.rb
core/spec/integration/loader/lexical_scope_spec.rb
core/spec/integration/loader/support/definable_state/comments_only.rb
core/spec/integration/loader/support/lexical_scope/nesting.rb
frameworks/data/spec/expectations/commands/bootstrap/help
frameworks/data/spec/expectations/commands/create/help
frameworks/data/spec/expectations/commands/drop/help
frameworks/data/spec/expectations/commands/finalize/help
frameworks/data/spec/expectations/commands/migrate/help
frameworks/data/spec/expectations/commands/reset/help
frameworks/data/spec/spec_helper.rb

`Pakyow::Loader` has been loading files with a `Module.nesting` that includes `Pakyow`. This causes all kinds of unexpected behavior, such as constant lookups resolving to objects in the `Pakyow` namespace from application code.
This PR changes the loading approach to behave expectedly. Here's how it works:
1. Define the constant for the new object.
2. Build a string containing the internal source for the new object.
3. Eval the object source in context of `TOPLEVEL_BINDING`.
Step 3 is what this PR changes. Previously `eval` happened in context of the `Pakyow::Loader::Context` instance binding.
There's a secondary change in that loading happens in the new `PakyowToplevel` lexical scope. This change allows constant lookup to behave correctly for _anonymous state_, delegating all constant …

Load files with the expected module nesting

---

.github/workflows/smoke-test.yml
.github/workflows/standardrb.yml
.github/workflows/test-node.yml
.github/workflows/test-ruby.yml
core/CHANGELOG.md
core/lib/pakyow/runnable/container/strategies/base.rb
core/lib/pakyow/runnable/container/strategies/forked.rb
core/lib/pakyow/runnable/service.rb
core/spec/integration/runnable/container/restarting_spec.rb

Solves two problems related to service restarts:
1. Automatically cancels any async work that was not waited on by `Service#perform`. This means that a service is responsible for blocking in its `perform` method—if `perform` returns the container assumes it is finished.
2. Prevents multiple exit notifications for forked services. This was causing exponential growth in services in some cases.

Improve the reliability of service restarts

---

core/CHANGELOG.md
core/lib/pakyow/verifier.rb
core/spec/unit/verifier_spec.rb

This allows a fallback to a default value even if `nil` cannot be coerced into the defined type.

Don't attempt to coerce nils in the verifier

---

core/CHANGELOG.md
core/lib/pakyow/environment.rb
core/spec/unit/environment_spec.rb

Mounted apps are tracked after `setup`, so make them available at that point for lookups.

Return mounted app after environment setup

---

core/CHANGELOG.md
core/lib/pakyow/actions/normalizer.rb
core/spec/unit/actions/normalizer_spec.rb

This is slightly more performant and resolves an issue when using canonical urls.

Initialize the normalizer with internal state rather than using config
