pakyow-ui/lib/pakyow-ui/ui_attrs.rb, pakyow-ui/lib/pakyow-ui/ui_instructable.rb, pakyow-ui/spec/integration/ui_view_transformation_spec.rb
Based on discussion in [this pr](https://github.com/pakyow/pakyow-js/pull/2) regarding #78.
=> Support bindings in ui

lib/pakyow/command_line_interface.rb, spec/features/command_line_interface_spec.rb
=> Add "pakyow version" command to CLI

lib/generators/pakyow/app/templates/middleware/req_path_normalizer.rb, pakyow-core/lib/core/call_context.rb, pakyow-core/lib/core/middleware/req_path_normalizer.rb, pakyow-core/lib/core/request.rb, pakyow-core/spec/spec_helper.rb, pakyow-core/spec/unit/middleware/req_path_normalizer_spec.rb
=> Handle requests paths like "//about" correctly

lib/pakyow/commands/console.rb, lib/pakyow/commands/server.rb
=> WIP: Make current environment more consistent

pakyow-core/lib/core/middleware/req_path_normalizer.rb, pakyow-core/spec/unit/middleware/req_path_normalizer_spec.rb
=> Remove trailing  in request path

pakyow-core/lib/core/helpers/running.rb, pakyow-core/spec/unit/helpers/running_spec.rb
Brings some sanity to `require` statements and fixes #153.
=> Add src_dir to load path

pakyow-mailer/lib/mailer/helpers.rb, pakyow-mailer/lib/mailer/mailer.rb, pakyow-mailer/spec/mail_mutator_spec.rb, pakyow-mailer/spec/mailer_spec.rb, pakyow-mailer/spec/support/helper.rb, pakyow-mailer/spec/support/test_application.rb, pakyow-mailer/spec/views/mutator.html
This makes it possible to use mutators to render views in mailer (#149).
=> Use ViewContext in mailer

Gemfile, lib/generators/pakyow/app/templates/app/views/_templates/default.html, pakyow-core/lib/core/helpers/running.rb, pakyow-core/lib/core/response.rb, pakyow-core/spec/cases/application/actions_spec.rb, pakyow-mailer/lib/mailer/ext/premailer/adapter/oga.rb, pakyow-mailer/lib/pakyow-mailer.rb, pakyow-presenter/lib/pakyow-presenter.rb, pakyow-presenter/lib/presenter/string_doc.rb, pakyow-presenter/lib/presenter/string_doc_parser.rb, pakyow-presenter/lib/presenter/view.rb, pakyow-presenter/lib/presenter/view_version.rb, pakyow-presenter/pakyow-presenter.gemspec, pakyow-presenter/spec/integration/binder_spec.rb, pakyow-presenter/spec/integration/binding_part_spec.rb, pakyow-presenter/spec/integration/presenter_spec.rb, pakyow-presenter/spec/integration/processor_spec.rb, pakyow-presenter/spec/integration/support/helpers/view_binding_helpers.rb, pakyow-presenter/spec/integration/support/int_helper.rb, pakyow-presenter/spec/integration/support/mixins/form_binding_specs.rb, pakyow-presenter/spec/integration/view_collection_spec.rb, pakyow-presenter/spec/integration/view_composer_spec.rb, pakyow-presenter/spec/integration/view_store_spec.rb, pakyow-test/spec/integration/routing_spec.rb
This is a start to implementing #124. I tried Ox, but it doesn't support everything we need. Oga is working well, aside from two failing tests that I need to fix up. Mailer is also broken since Premailer doesn't have an adapter for Oga (we were using the Nokogiri adapter). I've [opened an issue](https://github.com/premailer/premailer/issues/283) on the Premailer project to ask for input before I set out to write an appropriate adapter.
If you try using this and have issues, let me know!
=> Replace Nokogiri with Oga

pakyow-presenter/lib/pakyow/presenter/ext/app.rb, pakyow-presenter/spec/integration/resource_bindings_spec.rb
See https://github.com/pakyow/pakyow/issues/181 for details.
=> Use resource name for binding set name

lib/generators/pakyow/app/templates/public/scripts/ring/LICENSE, lib/generators/pakyow/app/templates/public/styles/pakyow-css/LICENSE, pakyow-core/LICENSE, pakyow-mailer/LICENSE, pakyow-presenter/LICENSE, pakyow-rake/LICENSE, pakyow-realtime/LICENSE, pakyow-support/LICENSE, pakyow-test/LICENSE, pakyow-ui/LICENSE
This time based from stable branch.
=> Update licenses to 2016

docs/config/_overview.md, pakyow-core/lib/pakyow/core/config/app.rb
Remove remaining vestiges of old app.all_views_visible configuration.
=> completely remove app.all_views_visible

pakyow-presenter/lib/pakyow/presenter/page.rb
=> Update front-matter regex to match start of string

docs/environment/mounting.md
=> [WIP] contributed to mounting.md

pakyow-support/lib/pakyow/support/defineable.rb
Add `Defineable::ClassApi#make` and `Defineable#make`.
Add some docs for `Defineable#initialize` and for `make`.
=> Add default implementations of `make`

pakyow-support/lib/pakyow/support/indifferentize.rb, pakyow-support/spec/unit/indifferent_hash_spec.rb
In regard to https://github.com/pakyow/pakyow/issues/246
=> make Pakyow::Support::IndifferentHash respect Hash interface

lib/pakyow/cli.rb
Okay, this PR is a mulligan of [a previous one](https://github.com/pakyow/pakyow/pull/218). It addresses issue #217.
@bryanp: The main thing that I'm wondering at this point is how to test things to make sure that my fixes didn't break anything. If I attempt to just run Pakyow server I get this error: "You must run the \`pakyow server\` command in the root directory of a Pakyow project."
=> Server help fixes redux

pakyow-support/lib/pakyow/support/configurable/config_group.rb
In reference to https://github.com/pakyow/pakyow/issues/256
=> use double underscores in ConfigGroup

lib/pakyow/error.rb, pakyow-presenter/lib/pakyow/presenter.rb, pakyow-presenter/lib/pakyow/presenter/exceptions.rb, pakyow-presenter/lib/pakyow/presenter/front_matter_parser.rb, pakyow-presenter/lib/pakyow/presenter/page.rb, pakyow-presenter/lib/pakyow/presenter/template.rb, pakyow-presenter/lib/pakyow/presenter/template_store.rb, pakyow-presenter/lib/pakyow/presenter/view.rb
This PR addresses the front matter changes described here: https://github.com/pakyow/pakyow/wiki/Presenter-API#front-matter.
=> Refactor front matter into separate parser

lib/pakyow/cli.rb, lib/pakyow/commands/server.rb, lib/pakyow/environment.rb, lib/pakyow/logger/colorizer.rb, pakyow-core/pakyow-core.gemspec, pakyow.gemspec, spec/features/cli_spec.rb, spec/unit/environment_spec.rb
Implements #219. Should work on all platforms, including Windows!
=> Restart server when a file changes

pakyow-data/CHANGELOG.md, pakyow-data/lib/pakyow/data/adapters/sql.rb, pakyow-data/lib/pakyow/data/adapters/sql/types.rb
* Be more explicit regarding `Types`
* Update use of dry-types constructor to use an object
---
=> Fix data types

pakyow-core/CHANGELOG.md, pakyow-core/spec/unit/error_spec.rb, pakyow-support/lib/pakyow/support/dependencies.rb
=> Use Gem.dir instead of Gem.default_dir

pakyow-support/CHANGELOG.md, pakyow-support/lib/pakyow/support/deprecation.rb, pakyow-support/lib/pakyow/support/deprecator.rb, pakyow-support/lib/pakyow/support/deprecator/global.rb, pakyow-support/lib/pakyow/support/deprecator/reporters/log.rb, pakyow-support/lib/pakyow/support/deprecator/reporters/null.rb, pakyow-support/lib/pakyow/support/deprecator/reporters/warn.rb, pakyow-support/spec/features/deprecator_spec.rb, pakyow-support/spec/unit/deprecation_spec.rb, pakyow-support/spec/unit/deprecator/reporters/null_spec.rb, pakyow-support/spec/unit/deprecator/reporters/warn_spec.rb, pakyow-support/spec/unit/deprecator_spec.rb
Provides a convenient way to collect and report deprecations.
=> Introduce Pakyow::Support::Deprecator

spec/smoke/startup_spec.rb, spec/smoke_helper.rb
Lets us define new smoke tests much more easily.
=> Add helper for running smoke tests

pakyow-support/lib/pakyow/support/configurable.rb, pakyow-support/lib/pakyow/support/configurable/config.rb, pakyow-support/lib/pakyow/support/configurable/setting.rb, pakyow-support/spec/integration/configurable_spec.rb
I merged this to the incorrect branch, doing it again to `master` 🙄
=> Update Configurable to be an extension, improve docs

pakyow-core/CHANGELOG.md, pakyow-core/lib/pakyow/operation.rb, pakyow-core/spec/features/operation/getters_setters_spec.rb, pakyow-core/spec/features/operation/halting_spec.rb, pakyow-core/spec/features/operation/instance_variables_spec.rb, pakyow-core/spec/features/operation_spec.rb
Operations are now initialized with their own internal state that can be changed independently of their initial values.
=> Read/Set operation state via getters/setters or instance variables

pakyow-core/CHANGELOG.md, pakyow-core/lib/pakyow/environment.rb, pakyow-core/spec/features/initializers_spec.rb, pakyow-core/spec/unit/environment_spec.rb, spec/spec_config.rb
=> Make the environment setup phase consistent with the app setup phase

pakyow-core/CHANGELOG.md, pakyow-core/lib/pakyow/application.rb, pakyow-core/lib/pakyow/behavior/running.rb, pakyow-core/lib/pakyow/environment.rb, pakyow-core/spec/failures/setup_fails_spec.rb, pakyow-core/spec/unit/app_spec.rb, pakyow-core/spec/unit/environment_spec.rb, pakyow-data/spec/context/migration_context.rb
Note that this breaks restartability, which will be addressed in an upcoming work.
=> Make each phase of the startup sequence idempotent

support/CHANGELOG.md, support/lib/pakyow/support/thread_localizer.rb, support/spec/unit/thread_localizer_spec.rb
Defines a single finalizer per object rather than one per localized value.
=> Improve thread localizer performance

docs/0002-frontend/0002-bindings/0001-understanding.md
I don't fully understand Pakyow yet so just guessing at the missing word 😅🏌️‍♂️
=> Fix missing word
